export const HOME_BATCH_1_LOADER_STARTED = 'HOME_BATCH_1_LOADER_STARTED';
export const HOME_BATCH_1_SUCCESS = 'HOME_BATCH_1_SUCCESS';
export const HOME_BATCH_1_ERROR = 'HOME_BATCH_1_ERROR';
export const SHOW_ALL_VENDORS_LOADER = 'SHOW_ALL_VENDORS_LOADER';
export const SHOW_ALL_VENDORS_SUCCESS = 'SHOW_ALL_VENDORS_SUCCESS';
export const SHOW_ALL_VENDORS_ERROR = 'SHOW_ALL_VENDORS_ERROR';
export const SHOW_ALL_VIDEOS_LOADER = 'SHOW_ALL_VIDEOS_LOADER';
export const SHOW_ALL_VIDEOS_SUCCESS = 'SHOW_ALL_VIDEOS_SUCCESS';
export const SHOW_ALL_VIDEOS_ERROR = 'SHOW_ALL_VIDEOS_ERROR';
export const SHOW_ALL_PRODUCTS_LOADER = 'SHOW_ALL_PRODUCTS_LOADER';
export const SHOW_ALL_PRODUCTS_SUCCESS = 'SHOW_ALL_PRODUCTS_SUCCESS';
export const SHOW_ALL_PRODUCTS_ERROR = 'SHOW_ALL_PRODUCTS_ERROR';
export const LOAD_HOME_BANNER_LOADER = 'LOAD_HOME_BANNER_LOADER';
export const LOAD_HOME_BANNER_SUCCESS = 'LOAD_HOME_BANNER_SUCCESS';
export const LOAD_HOME_BANNER_ERROR = 'LOAD_HOME_BANNER_ERROR';
export const TOGGLE_MOBILE_SEARCH_MODAL = 'TOGGLE_MOBILE_SEARCH_MODAL';

/**
 * Vendor constants
 */
export const FETCH_VENDOR_LOADER_STARTED = 'FETCH_VENDOR_LOADER_STARTED';
export const FETCH_VENDOR_SUCCESS = 'FETCH_VENDOR_SUCCESS';
export const FETCH_VENDOR_ERROR = 'FETCH_VENDOR_ERROR';
export const FETCH_VENDOR_DETAILS_LOADER_STARTED = 'FETCH_VENDOR_DETAILS_LOADER_STARTED';
export const FETCH_VENDOR_DETAILS_SUCCESS = 'FETCH_VENDOR_DETAILS_SUCCESS';
export const FETCH_VENDOR_DETAILS_ERROR = 'FETCH_VENDOR_DETAILS_ERROR';
export const FETCH_SIMILAR_VENDOR_LOADER = 'FETCH_SIMILAR_VENDOR_LOADER';
export const FETCH_SIMILAR_VENDOR_SUCCESS = 'FETCH_SIMILAR_VENDOR_SUCCESS';
export const FETCH_SIMILAR_VENDOR_ERROR = 'FETCH_SIMILAR_VENDOR_ERROR';
export const SHOW_ALL_VIDEO_VENDOR_LOADER = 'SHOW_ALL_VIDEO_VENDOR_LOADER';
export const SHOW_ALL_VIDEO_VENDOR_SUCCESS = 'SHOW_ALL_VIDEO_VENDOR_SUCCESS';
export const SHOW_ALL_VIDEO_VENDOR_ERROR = 'SHOW_ALL_VIDEO_VENDOR_ERROR';
export const SHOW_ALL_ARTICLES_VENDOR_LOADER = 'SHOW_ALL_ARTICLES_VENDOR_LOADER';
export const SHOW_ALL_ARTICLES_VENDOR_SUCCESS = 'SHOW_ALL_ARTICLES_VENDOR_SUCCESS';
export const SHOW_ALL_ARTICLES_VENDOR_ERROR = 'SHOW_ALL_ARTICLES_VENDOR_ERROR';
export const SHOW_ALL_IMAGES_VENDOR_LOADER = 'SHOW_ALL_IMAGES_VENDOR_LOADER';
export const SHOW_ALL_IMAGES_VENDOR_SUCCESS = 'SHOW_ALL_IMAGES_VENDOR_SUCCESS';
export const SHOW_ALL_IMAGES_VENDOR_ERROR = 'SHOW_ALL_IMAGES_VENDOR_ERROR';
export const DELETE_REVIEW_LOADER = 'DELETE_REVIEW_LOADER';
export const DELETE_REVIEW_SUCCESS = 'DELETE_REVIEW_SUCCESS';
export const DELETE_REVIEW_ERROR = 'DELETE_REVIEW_ERROR';

/**
 * Filter constants
 * @type {string}
 */
export const FILTER_VENDOR_LOADER = 'FILTER_VENDOR_LOADER';
export const FILTER_VENDOR_SUCCESS = 'FILTER_VENDOR_SUCCESS';
export const FILTER_VENDOR_ERROR = 'FILTER_VENDOR_ERROR';


/**
 * User contants
 */
export const FETCH_USER_LOADER_STARTED = 'FETCH_USER_LOADER_STARTED';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_ERROR = 'FETCH_USER_ERROR';
export const TOGGLE_LOGIN_MODAL = 'TOGGLE_LOGIN_MODAL';
export const GET_WISHLIST_LOADER = 'GET_WISHLIST_LOADER';
export const GET_WISHLIST_SUCCESS = 'GET_WISHLIST_SUCCESS';
export const GET_WISHLIST_ERROR = 'GET_WISHLIST_ERROR';
export const UPDATE_USER_DATA_LOADER_STARTED = 'UPDATE_USER_DATA_LOADER_STARTED';
export const UPDATE_USER_DATA_SUCCESS = 'UPDATE_USER_DATA_SUCCESS';
export const UPDATE_USER_DATA_ERROR = 'UPDATE_USER_DATA_ERROR';
export const LOAD_MORE_USER_LOADER = 'LOAD_MORE_USER_LOADER';
export const LOAD_MORE_USER_SUCCESS = 'LOAD_MORE_USER_SUCCESS';
export const LOAD_MORE_USER_ERROR = 'LOAD_MORE_USER_ERROR';


/**
 * Me constants
 * @type {string}
 */
export const LIKE_DISLIKE_EXPERIENCE_VIDEO_LOADER = 'LIKE_DISLIKE_EXPERIENCE_VIDEO_LOADER';
export const LIKE_DISLIKE_EXPERIENCE_VIDEO_SUCCESS = 'LIKE_DISLIKE_EXPERIENCE_VIDEO_SUCCESS';
export const LIKE_DISLIKE_EXPERIENCE_VIDEO_ERROR = 'LIKE_DISLIKE_EXPERIENCE_VIDEO_ERROR';
export const LIKE_DISLIKE_VENDOR_LOADER = 'LIKE_DISLIKE_VENDOR_LOADER';
export const LIKE_DISLIKE_VENDOR_SUCCESS = 'LIKE_DISLIKE_VENDOR_SUCCESS';
export const LIKE_DISLIKE_VENDOR_ERROR = 'LIKE_DISLIKE_VENDOR_ERROR';
export const FOLLOW_UNFOLLOW_USER_LOADER = 'FOLLOW_UNFOLLOW_USER_LOADER';
export const FOLLOW_UNFOLLOW_USER_SUCCESS = 'FOLLOW_UNFOLLOW_USER_SUCCESS';
export const FOLLOW_UNFOLLOW_USER_ERROR = 'FOLLOW_UNFOLLOW_USER_ERROR';
export const FOLLOW_UNFOLLOW_VENDOR_LOADER = 'FOLLOW_UNFOLLOW_VENDOR_LOADER';
export const FOLLOW_UNFOLLOW_VENDOR_SUCCESS = 'FOLLOW_UNFOLLOW_VENDOR_SUCCESS';
export const FOLLOW_UNFOLLOW_VENDOR_ERROR = 'FOLLOW_UNFOLLOW_VENDOR_ERROR';
export const LIKE_REVIEW_LOADER = 'LIKE_REVIEW_LOADER';
export const LIKE_REVIEW_SUCCESS = 'LIKE_REVIEW_SUCCESS';
export const LIKE_REVIEW_ERROR = 'LIKE_REVIEW_ERROR';
export const ADD_COMMENT_REVIEW_LOADER = 'ADD_COMMENT_REVIEW_LOADER';
export const ADD_COMMENT_REVIEW_SUCCESS = 'ADD_COMMENT_REVIEW_SUCCESS';
export const ADD_COMMENT_REVIEW_ERROR = 'ADD_COMMENT_REVIEW_ERROR';
export const TOGGLE_SHARE_MODAL = 'TOGGLE_SHARE_MODAL';
export const LOGOUT_USER = 'LOGOUT_USER';
export const TOGGLE_PICTURE_MODAL = 'TOGGLE_PICTURE_MODAL';
export const PRODUCT_LIKE_REVIEW_LOADER = 'PRODUCT_LIKE_REVIEW_LOADER';
export const PRODUCT_LIKE_REVIEW_SUCCESS = 'PRODUCT_LIKE_REVIEW_SUCCESS';
export const PRODUCT_LIKE_REVIEW_ERROR = 'PRODUCT_LIKE_REVIEW_ERROR';

/**
 * Search constants
 */
export const SEARCH_LOADER_STARTED = 'SEARCH_LOADER_STARTED';
export const SEARCH_LOADER_SUCCESS = 'SEARCH_LOADER_SUCCESS';
export const SEARCH_LOADER_ERROR = 'SEARCH_LOADER_ERROR';

/**
 * Login constants
 */
export const GOOGLE_USER_LOGGING_UP_LOADER_ACTIVATED = 'GOOGLE_USER_LOGGING_UP_LOADER_ACTIVATED';
export const GOOGLE_USER_LOGGING_UP_SUCCESS = 'GOOGLE_USER_LOGGING_UP_SUCCESS';
export const GOOGLE_USER_LOGGING_UP_ERROR = 'GOOGLE_USER_LOGGING_UP_ERROR';
export const FACEBOOK_USER_LOGGING_UP_LOADER_ACTIVATED = 'FACEBOOK_USER_LOGGING_UP_LOADER_ACTIVATED';
export const FACEBOOK_USER_LOGGING_UP_SUCCESS = 'FACEBOOK_USER_LOGGING_UP_SUCCESS';
export const FACEBOOK_USER_LOGGING_UP_ERROR = 'FACEBOOK_USER_LOGGING_UP_ERROR';
export const CHECK_USER_TOKEN_LOADER_STARTED = 'CHECK_USER_TOKEN_LOADER_STARTED';
export const CHECK_USER_TOKEN_SUCCESS = 'CHECK_USER_TOKEN_SUCCESS';
export const CHECK_USER_TOKEN_ERROR = 'CHECK_USER_TOKEN_ERROR';
export const SIGN_UP_LOADER = 'SIGN_UP_LOADER';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_ERROR = 'SIGN_UP_ERROR';
export const EMAIL_LOGIN_LOADER = 'EMAIL_LOGIN_LOADER';
export const EMAIL_LOGIN_SUCCESS = 'EMAIL_LOGIN_SUCCESS';
export const EMAIL_LOGIN_ERROR = 'EMAIL_LOGIN_ERROR';


/**
 * Article constants
 **/
export const FETCH_ARTICLE_LOADER = 'FETCH_ARTICLE_LOADER';
export const FETCH_ARTICLE_SUCCESS = 'FETCH_ARTICLE_SUCCESS';
export const FETCH_ARTICLE_ERROR = 'FETCH_ARTICLE_ERROR';
export const ARTICLE_ACTION_LOADER = 'ARTICLE_ACTION_LOADER';
export const ARTICLE_ACTION_SUCCESS = 'ARTICLE_ACTION_SUCCESS';
export const ARTICLE_ACTION_ERROR = 'ARTICLE_ACTION_ERROR';

/**
 SimilarArticles constant* 
**/

export const FETCH_SIMILAR_ARTICLES_API_LOADER = 'FETCH_SIMILAR_ARTICLES_API_LOADER';
export const FETCH_SIMILAR_ARTICLES_API_SUCCESS = 'FETCH_SIMILAR_ARTICLES_API_SUCCESS';
export const FETCH_SIMILAR_ARTICLES_API_ERROR = 'FETCH_SIMILAR_ARTICLES_API_ERROR';
export const SIMILAR_ARTICLES_API_LOADER = 'SIMILAR_ARTICLES_API_LOADER';
export const SIMILAR_ARTICLES_API_SUCCESS = 'SIMILAR_ARTICLES_API_SUCCESS';
export const SIMILAR_ARTICLES_API_ERROR = 'SIMILAR_ARTICLES_API_ERROR';

/**
 * trending article
 */

export const TRENDING_ARTICLES_API_LOADER = 'TRENDING_ARTICLES_API_LOADER';
export const TRENDING_ARTICLES_API_SUCCESS = 'TRENDING_ARTICLES_API_SUCCESS';
export const TRENDING_ARTICLES_API_ERROR = 'TRENDING_ARTICLES_API_ERROR';

/**
 * Review Constants
 */
export const ADD_REVIEW_LOADER = 'ADD_REVIEW_LOADER';
export const ADD_REVIEW_SUCCESS = 'ADD_REVIEW_SUCCESS';
export const ADD_REVIEW_ERROR = 'ADD_REVIEW_ERROR';
export const ADD_REVIEW_PRODIUCT_LOADER = 'ADD_REVIEW_PRODIUCT_LOADER';
export const ADD_REVIEW_PRODIUCT_SUCCESS = 'ADD_REVIEW_PRODIUCT_SUCCESS';
export const ADD_REVIEW_PRODIUCT_ERROR = 'ADD_REVIEW_PRODIUCT_ERROR';


/**
 * Product Constants
 */
export const FETCH_PRODUCT_LOADER = 'FETCH_PRODUCT_LOADER';
export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS';
export const FETCH_PRODUCT_ERROR = 'FETCH_PRODUCT_ERROR';
export const SAVE_PRODUCT_WISHLIST_LOADER = 'SAVE_PRODUCT_WISHLIST_LOADER';
export const SAVE_PRODUCT_WISHLIST_SUCCESS = 'SAVE_PRODUCT_WISHLIST_SUCCESS';
export const SAVE_PRODUCT_WISHLIST_ERROR = 'SAVE_PRODUCT_WISHLIST_ERROR';
export const FETCH_PRODUCTS_VENDOR_LOADER = 'FETCH_PRODUCTS_VENDOR_LOADER';
export const FETCH_PRODUCTS_VENDOR_SUCCESS = 'FETCH_PRODUCTS_VENDOR_SUCCESS';
export const FETCH_PRODUCTS_VENDOR_ERROR = 'FETCH_PRODUCTS_VENDOR_ERROR';
export const FETCH_SIMILAR_PRODUCT_LOADER = 'FETCH_SIMILAR_PRODUCT_LOADER';
export const FETCH_SIMILAR_PRODUCT_SUCCESS = 'FETCH_SIMILAR_PRODUCT_SUCCESS';
export const FETCH_SIMILAR_PRODUCT_ERROR = 'FETCH_SIMILAR_PRODUCT_ERROR';
export const ADD_TO_CART_LOADER = 'ADD_TO_CART_LOADER';
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';
export const ADD_TO_CART_ERROR = 'ADD_TO_CART_ERROR';
export const FETCH_CART_LOADER = 'FETCH_CART_LOADER';
export const FETCH_CART_SUCCESS = 'FETCH_CART_SUCCESS';
export const FETCH_CART_ERROR = 'FETCH_CART_ERROR';
export const UPDATE_EMAIL_CART_LOADER = 'UPDATE_EMAIL_CART_LOADER';
export const UPDATE_EMAIL_CART_SUCCESS = 'UPDATE_EMAIL_CART_SUCCESS';
export const UPDATE_EMAIL_CART_ERROR = 'UPDATE_EMAIL_CART_ERROR';
export const UPDATE_SHIPPING_ADDRESS_SUCCESS = 'UPDATE_SHIPPING_ADDRESS_SUCCESS';
export const UPDATE_ITEM_QUANTITY_SUCCESS = 'UPDATE_ITEM_QUANTITY_SUCCESS';
export const REMOVE_ITEM_CART_SUCCESS = 'REMOVE_ITEM_CART_SUCCESS';
export const EMPTY_CART = 'EMPTY_CART';
export const FETCH_SERVICES_LOADING = 'FETCH_SERVICES_LOADING';
export const FETCH_SERVICES_SUCCESS = 'FETCH_SERVICES_SUCCESS';
export const FETCH_SERVICES_ERROR = 'FETCH_SERVICES_ERROR';
export const LOAD_MORE_PRODUCT_REVIEWS_LOADER = 'LOAD_MORE_PRODUCT_REVIEWS_LOADER';
export const LOAD_MORE_PRODUCT_REVIEWS_SUCCESS = 'LOAD_MORE_PRODUCT_REVIEWS_SUCCESS';
export const LOAD_MORE_PRODUCT_REVIEWS_ERROR = 'LOAD_MORE_PRODUCT_REVIEWS_ERROR';


/**
 * Admin constants
 */
export const FETCH_VENDOR_ADMIN_LOADER_STARTED = 'FETCH_VENDOR_ADMIN_LOADER_STARTED';
export const FETCH_VENDOR_ADMIN_SUCCESS = 'FETCH_VENDOR_ADMIN_SUCCESS';
export const FETCH_VENDOR_ADMIN_ERROR = 'FETCH_VENDOR_ADMIN_ERROR';
export const UPDATE_VENDOR_LOADER_STARTED = 'UPDATE_VENDOR_LOADER_STARTED ';
export const UPDATE_VENDOR_SUCCESS = 'UPDATE_VENDOR_SUCCESS';
export const UPDATE_VENDOR_ERROR = 'UPDATE_VENDOR_ERROR';
export const SAVE_IMAGES_LOADER = 'SAVE_IMAGES_LOADER';
export const SAVE_IMAGES_SUCCESS = 'SAVE_IMAGES_SUCCESS';
export const SAVE_IMAGES_ERROR = 'SAVE_IMAGES_ERROR';
export const SAVE_PRODUCT_DASHBOARD_LOADER = 'SAVE_PRODUCT_DASHBOARD_LOADER';
export const SAVE_PRODUCT_DASHBOARD_SUCCESS = 'SAVE_PRODUCT_DASHBOARD_SUCCESS';
export const SAVE_PRODUCT_DASHBOARD_ERROR = 'SAVE_PRODUCT_DASHBOARD_ERROR';
export const DELETE_IMAGE_LOADER = 'DELETE_IMAGE_LOADER';
export const DELETE_IMAGE_SUCCESS = 'DELETE_IMAGE_SUCCESS';
export const DELETE_IMAGE_ERROR = 'DELETE_IMAGE_ERROR';


/**
 * Video Constants
 */
export const FETCH_VIDEO_LOADER = 'FETCH_VIDEO_LOADER';
export const FETCH_VIDEO_SUCCESS = 'FETCH_VIDEO_SUCCESS';
export const FETCH_VIDEO_ERROR = 'FETCH_VIDEO_ERROR';
export const ADD_COMMENT_LOADER = 'ADD_COMMENT_LOADER';
export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS';
export const ADD_COMMENT_ERROR = 'ADD_COMMENT_ERROR';
export const FETCH_COMMENTS_LOADER = 'FETCH_COMMENTS_LOADER';
export const FETCH_COMMENTS_SUCCESS = 'FETCH_COMMENTS_SUCCESS';
export const FETCH_COMMENTS_ERROR = 'FETCH_COMMENTS_ERROR';
export const COMMENT_ACTION_LOADER = 'COMMENT_ACTION_LOADER';
export const COMMENT_ACTION_SUCCESS = 'COMMENT_ACTION_SUCCESS';
export const COMMENT_ACTION_ERROR = 'COMMENT_ACTION_ERROR';


/**
 * Review Constants
 **/
export const FETCH_REVIEW_LOADER = 'FETCH_REVIEW_LOADER';
export const FETCH_REVIEW_SUCCESS = 'FETCH_REVIEW_SUCCESS';
export const FETCH_REVIEW_ERROR = 'FETCH_REVIEW_ERROR';
export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS';

export const FETCH_ALL_ARTICLES_LOADER = 'FETCH_ALL_ARTICLES_LOADER';
export const FETCH_ALL_ARTICLES_SUCCESS = 'FETCH_ALL_ARTICLES_SUCCESS';
export const FETCH_ALL_ARTICLES_ERROR = 'FETCH_ALL_ARTICLES_ERROR';
